from action import *

action = Action()
# action.open_muilty_manager()
# action.standby(1)
# action.emulator_start_up()
# action.standby(8)
# action.start_mapleM()
# action.standby(40)
# action.close_events()
# action.click_logo()
# action.choose_world()
# action.start_game()
# action.auto_fight_result()
# action.auto_fight()
# action.auto_fight_use()
action.auto_fight_start()